### ISSUE TITLE
Dockerfile out of date

### ISSUE THREAD

**Issue by JimBobUKII** [awesometic/docker-docusaurus#10]
It seems your Dockerfile located here is out of date. Please update

**Comment by awesometic** [comment]
Hi,

Sorry, but what's mean that you referring 'out of date'? 🤔 
Today I updated my Dockerfile to update the base image to Alpine 3.16. Hope it is that you meant.

**Comment by awesometic** [comment]
Since there is no update for this issue, I will close this one 😃
